---
- name: Ensure the focal-security repository is added
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/focal-security.list
    line: "deb http://security.ubuntu.com/ubuntu focal-security main"
    create: yes

- name: Install dependencies for mongodb
  ansible.builtin.apt:
    pkg:
      - gnupg
      - libssl1.1
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    update_cache: yes

- name: Download MongoDB GPG key
  ansible.builtin.get_url:
    url: "https://www.mongodb.org/static/pgp/server-7.0.asc"
    dest: "/tmp/mongodb-server-7.0.asc"
    validate_certs: no

- name: Import MongoDB GPG key
  ansible.builtin.shell: "sh -c 'gpg --dearmor < /tmp/mongodb-server-7.0.asc > /usr/share/keyrings/mongodb-server-7.0.gpg'"

- name: Add MongoDB repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/mongodb-org-7.0.list
    line: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
    create: yes

- name: Install mongodb
  apt:
    pkg: mongodb-org
    state: latest
    update_cache: yes
  notify:
    - start mongodb

- name: Merge default config with host-specific config
  set_fact:
    merged_config: "{{ default_config | combine(hostvars[inventory_hostname].config | default({})) }}"

- name: Create the mongodb configuration file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
