---
- name: Install mongodb
  include_tasks: install.yaml
  when: action_type == "install" or action_type == "full"

- name: Configure mongodb
  include_tasks: configure.yaml
  when: action_type == "configure" or action_type == "full"

- name: Uninstall all mongodb-related files
  include_tasks: revert.yaml
  when: action_type == "revert"
