---
default_config:
  # System Log
  # destination
  destination: file
  path: "/var/log/mongodb/mongod.log"
  logAppend: "true"

  # Process Management
  fork: "true"

  # Network
  bindIp: 127.0.0.1
  port: 27017
  bindIpAll: "false"

  # Security
  clusterAuthMode: keyFile
  authorization: disabled
  transitionToAuth: "false"
  javascriptEnabled: "true"
  clusterIpSourceAllowlist: # no default value

  # Set Parameter
  enableLocalhostAuthBypass: "false"

  # Storage
  dbPath: "/data/db"
  commitIntervalMs: 100
  directoryPerDB: "false"
  syncPeriodSecs: 60
  engine: wiredTiger
  journalCompressor: snappy
  directoryForIndexes: "false"
  maxCacheOverflowFileSizeGB: 6
  blockCompressor: snappy
  prefixCompression: "true"
  inMemorySizeGB: # no default value

  # Operation Profiling
  mode: "off"
  slowOpThresholdMs: 100
  slowOpSampleRate: 1.0
  filter: # no default value

  # Sharding
  clusterRole: # no default value
  archiveMovedChunks: "false"
  configDB: # no default value
