---
# full = install + configure
action_type: full # possible options: full, install, configure, revert

mongodb_version: 7.0
default_config:
  systemLog:
    destination: "file"
    path: "/var/log/mongodb/mongod.log"
    logAppend: "true"
  net:
    port: 27017
    bindIp: "127.0.0.1"
    bindIpAll: "false"
  security:
    authorization: "disabled"
    javascriptEnabled: "true"
  storage:
    dbPath: "/var/lib/mongodb"
    journal:
      commitIntervalMs: 100
    directoryPerDB: "false"
    syncPeriodSecs: 60
    engine: "wiredTiger"
    wiredTiger:
      engineConfig:
        journalCompressor: "snappy"
        directoryForIndexes: "false"
        maxCacheOverflowFileSizeGB: 6
      collectionConfig:
        blockCompressor: "snappy"
      indexConfig:
        prefixCompression: "true"
  operationProfiling:
    mode: "off"
    slowOpThresholdMs: 100
    slowOpSampleRate: 1.0
  sharding:
    archiveMovedChunks: "false"
