all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    database:
      hosts:
        ansible_experiments-playground-1:
          ansible_host: ansible_experiments-playground-1
          ansible_user: bilbo
          ansible_password: 1
          config:
            logAppend: "false"
        ansible_experiments-playground-2:
          ansible_host: ansible_experiments-playground-2
          ansible_user: bilbo
          ansible_password: 1
          config:
            fork: "false"
